# Generated by Django 3.2.7 on 2021-09-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0133_port_colors'),
        ('tenancy', '0001_squashed_0012'),
        ('phonebox_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='number',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='number',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='number',
            unique_together=set(),
        ),
    ]
