# Generated by Django 5.1.5 on 2025-02-18 23:47

import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebox_plugin', '0004_alter_number_created_alter_number_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='voicecircuit',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
