# Generated by Django 5.1.5 on 2025-02-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('phonebox_plugin', '0005_number_custom_field_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_set', to='dcim.site'),
        ),
    ]
